version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    # ports:
    #   - 5432:5432
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - wingbook
  server:
    build:
      context: ../server/
      dockerfile: Dockerfile
    ports:
      - 8012:8000
    env_file:
      - .env
    networks:
      - wingbook
    depends_on:
      - postgres
    volumes:
      - ../server/wingbook/api/migrations:/app/wingbook/api/migrations
  front:
    build:
      context: ../front/
      dockerfile: Dockerfile
    ports:
      - 8013:3000
    env_file:
      - .env

networks:
  wingbook: