# Generated by Django 5.2.1 on 2025-05-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('se_duration', models.DurationField()),
                ('me_duration', models.DurationField()),
                ('multi_pilot_duration', models.DurationField()),
                ('flight_duration', models.DurationField()),
                ('landing_day_num', models.IntegerField()),
                ('landing_night_num', models.IntegerField()),
                ('ifr_apch_num', models.IntegerField()),
                ('night_duration', models.DurationField()),
                ('ifr_duration', models.DurationField()),
                ('pilot_in_command_duration', models.DurationField()),
                ('copilot_duration', models.DurationField()),
                ('dual_duration', models.DurationField()),
                ('instructor_duration', models.DurationField()),
                ('simulator_date', models.DateField()),
                ('simulator_type', models.CharField(max_length=100)),
                ('simulator_duration', models.DurationField()),
                ('comments', models.TextField()),
                ('pilot_in_command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_in_command', to='api.person')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plane')),
            ],
        ),
    ]
