# Generated by Django 5.2.1 on 2025-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_unique_together_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulator_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulator_duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulator_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
