# Generated by Django 5.2.1 on 2025-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_flight_comments_alter_flight_simulator_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='simulator_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulator_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulator_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
