# Generated by Django 5.2.1 on 2025-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_flight_simulator_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='single_engine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plane',
            name='single_pilot',
            field=models.BooleanField(default=True),
        ),
    ]
