# Generated by Django 5.2.1 on 2025-05-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plane_single_engine_plane_single_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='copilot_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dual_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ifr_apch_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ifr_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instructor_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_day_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_night_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='me_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='multi_pilot_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='night_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='pilot_in_command_duration',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='se_duration',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
