# Generated by Django 5.2.1 on 2025-05-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_flight_copilot_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='api.person'),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
