# Generated by Django 5.2.1 on 2025-05-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_flight_passengers_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
