# Generated by Django 5.2.1 on 2025-05-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_account_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
