# Generated by Django 5.2.1 on 2025-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_account_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_main_account',
            field=models.BooleanField(default=False),
        ),
    ]
