# Generated by Django 5.2.1 on 2025-05-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_account_is_main_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_main_account',
        ),
        migrations.AddField(
            model_name='plane',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.account'),
        ),
    ]
