# Generated by Django 5.2.1 on 2025-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_transaction_transaction_type_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('refund', 'Refund'), ('transfer', 'Transfer')], max_length=100),
        ),
    ]
