# Generated by Django 5.2.1 on 2025-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='operations',
            field=models.ManyToManyField(blank=True, to='api.operation'),
        ),
    ]
