# Generated by Django 5.2.1 on 2025-05-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_flight_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='operations',
        ),
        migrations.AddField(
            model_name='operation',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flight'),
        ),
    ]
